import os
import sys
import json
import shutil
import subprocess
from pathlib import Path

from path_utils import PROJECT_ROOT, SRC_DIR, TESTS_DIR, TEST_TEMP_DIR, TEST_INPUTS_DIR, TEST_REPORTS_DIR, add_src_to_path

add_src_to_path()

TEST_ROOT = str(TESTS_DIR)
TEMP_DIR = str(TEST_TEMP_DIR / "real_tool_smoke")
INPUT_DIR = str(TEST_INPUTS_DIR)
REPORT_DIR = str(TEST_REPORTS_DIR)

os.makedirs(TEMP_DIR, exist_ok=True)
os.makedirs(REPORT_DIR, exist_ok=True)

REPORT = {
    "smiles_to_sdf": None,
    "sdf_to_xyz": None,
    "xyz_to_gjf": None,
    "openbabel_cli": None,
}

def write_file(path: str, content: str):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

def run_cmd(cmd, cwd=None):
    try:
        proc = subprocess.run(
            cmd,
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=120
        )
        return {
            "ok": proc.returncode == 0,
            "returncode": proc.returncode,
            "stdout": proc.stdout,
            "stderr": proc.stderr,
            "cmd": cmd,
        }
    except Exception as e:
        return {
            "ok": False,
            "returncode": None,
            "stdout": "",
            "stderr": str(e),
            "cmd": cmd,
        }

def try_openbabel_cli():
    obabel = shutil.which("obabel") or shutil.which("babel")
    if not obabel:
        return {
            "ok": False,
            "reason": "obabel/babel not found in PATH"
        }

    smi_path = os.path.join(TEMP_DIR, "ethanol.smi")
    sdf_path = os.path.join(TEMP_DIR, "ethanol_from_obabel.sdf")

    write_file(smi_path, "CCO\tethanol\n")

    # Open Babel command may differ slightly by install
    cmd = [obabel, smi_path, "-O", sdf_path, "--gen3d"]
    result = run_cmd(cmd)

    result["output_exists"] = os.path.exists(sdf_path)
    result["output_path"] = sdf_path
    return result

def try_rdkit_smiles_to_sdf():
    try:
        from rdkit import Chem
        from rdkit.Chem import AllChem
    except Exception as e:
        return {"ok": False, "reason": f"RDKit import failed: {e}"}

    try:
        smiles = "CCO"
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return {"ok": False, "reason": "RDKit failed to parse SMILES"}
        mol = Chem.AddHs(mol)
        AllChem.EmbedMolecule(mol, randomSeed=42)
        AllChem.UFFOptimizeMolecule(mol)

        sdf_path = os.path.join(TEMP_DIR, "ethanol_rdkit.sdf")
        writer = Chem.SDWriter(sdf_path)
        writer.write(mol)
        writer.close()

        return {
            "ok": os.path.exists(sdf_path),
            "output_path": sdf_path,
        }
    except Exception as e:
        return {"ok": False, "reason": str(e)}

def try_rdkit_sdf_to_xyz():
    try:
        from rdkit import Chem
    except Exception as e:
        return {"ok": False, "reason": f"RDKit import failed: {e}"}

    sdf_path = os.path.join(TEMP_DIR, "ethanol_rdkit.sdf")
    if not os.path.exists(sdf_path):
        return {"ok": False, "reason": "missing input SDF from previous step"}

    try:
        suppl = Chem.SDMolSupplier(sdf_path, removeHs=False)
        mol = suppl[0]
        if mol is None:
            return {"ok": False, "reason": "failed to read SDF"}

        conf = mol.GetConformer()
        xyz_path = os.path.join(TEMP_DIR, "ethanol.xyz")

        lines = [str(mol.GetNumAtoms()), "generated by RDKit"]
        for atom in mol.GetAtoms():
            pos = conf.GetAtomPosition(atom.GetIdx())
            lines.append(f"{atom.GetSymbol()} {pos.x:.6f} {pos.y:.6f} {pos.z:.6f}")

        write_file(xyz_path, "\n".join(lines) + "\n")

        return {
            "ok": os.path.exists(xyz_path),
            "output_path": xyz_path,
        }
    except Exception as e:
        return {"ok": False, "reason": str(e)}

def try_xyz_to_gjf():
    xyz_path = os.path.join(TEMP_DIR, "ethanol.xyz")
    if not os.path.exists(xyz_path):
        return {"ok": False, "reason": "missing input XYZ from previous step"}

    try:
        with open(xyz_path, "r", encoding="utf-8") as f:
            xyz_lines = f.readlines()

        coord_lines = xyz_lines[2:]  # skip atom count and title
        gjf_path = os.path.join(TEMP_DIR, "ethanol.gjf")

        route = "#p B3LYP/6-31G(d) Opt Freq"
        content = []
        content.append("%chk=ethanol.chk")
        content.append(route)
        content.append("")
        content.append("Ethanol test job")
        content.append("")
        content.append("0 1")
        content.extend([line.strip() for line in coord_lines if line.strip()])
        content.append("")
        content.append("")

        write_file(gjf_path, "\n".join(content))

        return {
            "ok": os.path.exists(gjf_path),
            "output_path": gjf_path,
        }
    except Exception as e:
        return {"ok": False, "reason": str(e)}

def main():
    print("========== Real Tool Smoke Tests ==========")
    print(f"PROJECT_ROOT: {PROJECT_ROOT}")
    print(f"SRC_DIR:      {SRC_DIR}")
    print("[INFO] These smoke tests probe optional real-tool dependencies and do not run Gaussian.")

    print("\n[1] Open Babel CLI smoke test")
    REPORT["openbabel_cli"] = try_openbabel_cli()
    print(json.dumps(REPORT["openbabel_cli"], indent=2, ensure_ascii=False))

    print("\n[2] RDKit SMILES -> SDF smoke test")
    REPORT["smiles_to_sdf"] = try_rdkit_smiles_to_sdf()
    print(json.dumps(REPORT["smiles_to_sdf"], indent=2, ensure_ascii=False))

    print("\n[3] RDKit SDF -> XYZ smoke test")
    REPORT["sdf_to_xyz"] = try_rdkit_sdf_to_xyz()
    print(json.dumps(REPORT["sdf_to_xyz"], indent=2, ensure_ascii=False))

    print("\n[4] XYZ -> GJF smoke test")
    REPORT["xyz_to_gjf"] = try_xyz_to_gjf()
    print(json.dumps(REPORT["xyz_to_gjf"], indent=2, ensure_ascii=False))

    report_path = os.path.join(REPORT_DIR, "real_tool_smoke_report.json")
    with open(report_path, "w", encoding="utf-8") as f:
        json.dump(REPORT, f, indent=2, ensure_ascii=False)

    print(f"\nSaved report to: {report_path}")

    all_ok = all(v and v.get("ok") for v in REPORT.values() if isinstance(v, dict))
    if all_ok:
        print("\nAll smoke tests passed.")
    else:
        print("\nSome smoke tests failed. Check the report for details.")

    print("===========================================")

if __name__ == "__main__":
    main()
